// <auto-generated />
using System;
using JevoGastosCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JevoGastosCore.Migrations
{
    [DbContext(typeof(GastosContext))]
    [Migration("20200603220822_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("JevoGastosCore.Model.Etiqueta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Total")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.HasKey("Id");

                    b.ToTable("Etiquetas");

                    b.HasDiscriminator<string>("Tipo").HasValue("Etiqueta");
                });

            modelBuilder.Entity("JevoGastosCore.Model.Transaccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<int>("DestinoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrigenId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("DestinoId");

                    b.HasIndex("OrigenId");

                    b.ToTable("Transacciones");
                });

            modelBuilder.Entity("JevoGastosCore.Model.Cuenta", b =>
                {
                    b.HasBaseType("JevoGastosCore.Model.Etiqueta");

                    b.HasDiscriminator().HasValue("Cuenta");
                });

            modelBuilder.Entity("JevoGastosCore.Model.Gasto", b =>
                {
                    b.HasBaseType("JevoGastosCore.Model.Etiqueta");

                    b.HasDiscriminator().HasValue("Gasto");
                });

            modelBuilder.Entity("JevoGastosCore.Model.Ingreso", b =>
                {
                    b.HasBaseType("JevoGastosCore.Model.Etiqueta");

                    b.HasDiscriminator().HasValue("Ingreso");
                });

            modelBuilder.Entity("JevoGastosCore.Model.Transaccion", b =>
                {
                    b.HasOne("JevoGastosCore.Model.Etiqueta", "Destino")
                        .WithMany("TransaccionesDestino")
                        .HasForeignKey("DestinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JevoGastosCore.Model.Etiqueta", "Origen")
                        .WithMany("TransaccionesOrigen")
                        .HasForeignKey("OrigenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
