// <auto-generated />
using System;
using JevoGastosCore.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JevoGastosCore.Migrations
{
    [DbContext(typeof(GastosContext))]
    [Migration("20200531025357_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("JevoGastosCore.Model.Etiqueta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoEtiquetaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TipoEtiquetaId");

                    b.ToTable("Etiquetas");
                });

            modelBuilder.Entity("JevoGastosCore.Model.TipoEtiqueta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TiposEtiquetas");
                });

            modelBuilder.Entity("JevoGastosCore.Model.TipoTransaccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("TDestinoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TOrigenId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TDestinoId");

                    b.HasIndex("TOrigenId");

                    b.ToTable("TiposTransacciones");
                });

            modelBuilder.Entity("JevoGastosCore.Model.Transaccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<int>("DestinoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrigenId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoTransaccionId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("DestinoId");

                    b.HasIndex("OrigenId");

                    b.HasIndex("TipoTransaccionId");

                    b.ToTable("Transacciones");
                });

            modelBuilder.Entity("JevoGastosCore.Model.Etiqueta", b =>
                {
                    b.HasOne("JevoGastosCore.Model.TipoEtiqueta", "TipoEtiqueta")
                        .WithMany("Etiquetas")
                        .HasForeignKey("TipoEtiquetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JevoGastosCore.Model.TipoTransaccion", b =>
                {
                    b.HasOne("JevoGastosCore.Model.TipoEtiqueta", "TDestino")
                        .WithMany("TTransaccionesDestino")
                        .HasForeignKey("TDestinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JevoGastosCore.Model.TipoEtiqueta", "TOrigen")
                        .WithMany("TTransaccionesOrigen")
                        .HasForeignKey("TOrigenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JevoGastosCore.Model.Transaccion", b =>
                {
                    b.HasOne("JevoGastosCore.Model.Etiqueta", "Destino")
                        .WithMany("TransaccionesDestino")
                        .HasForeignKey("DestinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JevoGastosCore.Model.Etiqueta", "Origen")
                        .WithMany("TransaccionesOrigen")
                        .HasForeignKey("OrigenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JevoGastosCore.Model.TipoTransaccion", "TipoTransaccion")
                        .WithMany("Transacciones")
                        .HasForeignKey("TipoTransaccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
